insert into category (name) values ('liha');
insert into category (name) values ('kala');
insert into category (name) values ('kasvis');
insert into category (name) values ('broileri');
insert into category (name) values ('keitto');
insert into category (name) values ('salaatti');
insert into category (name) values ('jälkiruoka');
insert into category (name) values ('leivonta');
insert into category (name) values ('juoma');

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Lihapullat uunissa', 'Lihapullat ja kermakastike on yksi kaikkien aikojen suosikkiresepteistä. Nämä maukkaat lihapullat maistuvat kaikille!', '2 dl vettä (tai kermaa tai kermaviiliä), 1 dl korppujauhoja, 1 kpl sipuli, 1 rkl, öljyä, 1 kpl kananmuna, 2 tl paprikajauhetta, 1 tl suolaa, 1/2 tl mustapippuria, 400 g jauhelihaa', 'Sekoita korppujauhot nesteeseen ja anna imeytyä. Kuori ja hienonna sipuli. Kuullota sipuli öljyssä pannulla. Lisää sipuli, muna, mausteet ja jauhelina korppujauhoseokseen. Sekoita tasaiseksi. Paista lihapullia uunissa 200 asteessa noin 10 minuuttia', 1);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Helppo särkikiusaus', 'Kotimaisesta särjestä ja pakasteperunoista syntyy vaivaton uuniruoka, joka on janssoninkiusauksen pikkuserkku.', '500 g peruna-sipulisuikaleita, 1 prk särkisäilykettä, 2 dl ruokakermaa, 3/4 tl suolaa, 1 tl rouhittua mustapippuria, 4 rkl hienonnettua tilliä', 'Säädä uuni 200 asteeseen. Kaada uunivuokaan puolet peruna-sipulisekoituksesta. Irrottele kala pienemmiksi paloiksi ja lisää vuokaan. Laita päälle loppu peruna-sipulisekoitus.Sekoita kerma, suola ja pippuri. Kaada vuokaan. Paista uunissa 45–60 minuuttia. Viimeistele tillillä.', 2);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Kesäkurpitsa-halloumipihvit ja limetti-jogurttikastike', 'Helpot kasvispihvit valmistuvat nopeasti kesäkurpitsasta ja halloumijuustosta. Näiden pihvien paistamiseen tarvitset vain muutaman aineksen. Nauti yhdessä limetti-jogurttikastikkeen kanssa.', '400 g kesäkurpitsaa, 200 g halloumijuustoa, 1 kpl kananmuna, oliiviöljyä paistamiseen, rucolasalaattia, LIMETTI-JOGURTTIKASTIKE: 2 dl turkkilaista jogurttia, limetin raastettu kuori ja mehu, suolaa, sokeria, rouhittua mustapippuria', 'Sekoita kastikkeen ainekset keskenään ja anna sen maustua pihvien teon ajan. Raasta kesäkurpitsa ja halloumi karkeaksi raasteeksi. Sekoita raasteet kulhossa kanamunan kanssa. Paista pannulla öljyssä miedolla lämmöllä pieniä pihvejä. Anna pihvien ruskistua molemmin puolin. Tarjoile limetti-jogurttikastikkeen ja rucolasalaatin kanssa.', 3);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Kaura-porkkanasämpylät', 'Mehevät kaura-porkkanasämpylät maistuvat tuoreina voin kera.', '3 dl omenamehua, 2 dl kermaviiliä, 50 g tuorehiivaa, 2 tl suolaa, 3 rkl hunajaa, 2 kpl porkkanaa, 10 dl sämpyläjauhoja, 2 1/2 dl kaurahiutaleita, 1 dl rypsiöljyä', 'Sekoita omenamehu ja kermaviili keskenään ja lämmitä seos kädenlämpöiseksi. Murenna joukkoon hiiva. Lisää suola ja hunaja. Kuori ja raasta porkkanat hienoksi, lisää joukkoon. Alusta sämpyläjauhot ja kaurahiutaleet taikinaan vähitellen vaivaten. Lisää lopuksi öljy. Anna kohota peitettynä lämpimässä paikassa kaksinkertaiseksi. Kaada taikina jauhotetulle alustalle ja leivo se kahdeksi tangoksi. Leikkaa tangot paloiksi ja pyöritä paloista sämpylöitä. Anna kohota peitettynä noin 20 minuuttia. Kuumenna uuni 225 asteeseen. Paista uunissa noin 10 minuuttia.', 8);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Kanakorma', 'Kanakorma on intialaisen keittiön klassikko.', '3 valkosipulinkynttä, 2 rkl tuoretta kurkumaa raastettuna, 2 rkl rypsiöljyä, 300 g broilerin fileesuikaleita, 3 rkl tomaattipyreetä, 1 tl juustokuminaa, 1/2 tl chilihiutaleita, 400 ml kookosmaitoa, 1 kanaliemikuutio, limemehua, ruukku korianteria', 'Kuori ja hienonna valkosipulinkynnet. Kuori ja raasta kurkuma raastimen pienimmällä terällä.Kuumenna öljy paistokasarissa. Lisää broilerin fileesuikaleet ja paista pari minuuttia sekoitellen. Lisää tomaattipyree, valkosipuli, kurkuma, juustokumina ja chilihiutaleet. Kaada joukkoon kookosmaito. Murustele sekaan kanaliemikuutio. Kypsennä keskilämmöllä 8–10 minuuttia. Purista joukkoon limemehu ja ripottele päälle hienonnettu korianteri. Mausta tarvittaessa suolalla. Tarjoa kanakorma basmatiriisin kanssa.', 4);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Kolmen sipulin keitto', 'Sipulikeitto on parasta, kun se on hautunut hiljakseen riittävän pitkään.', '6 salottisipulia, 4 keltasipulia, 5 valkosipulinkynttä, 1 rkl öljyä, 1 rkl voita, sokeria, 1 l kasvislientä, 1 dl valkoviiniä, 1/2 tl timjamia, mustapippuria myllystä, 1/2 tl suolaa', 'Kuori ja leikkaa sipulit ohuiksi viipaleiksi. Silppua valkosipulinkynnet. Kuullota sipulit voi-öljyseoksessa pehmeiksi, mutta älä ruskista. Lisää ripaus sokeria ja kuumenna hetki. Kaada kattilaan liemi (ja viini). Lisää mausteet. Anna keiton hautua hiljalleen 30–40 minuuttia. Tarkista maku ja lisää mausteita tai nestettä tarvittaessa.', 5);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Kukkakaali-vesimelonisalaatti', 'Sekoita grilliruoan kaveriksi kevyt ja raikas lisukesalaatti melonista, kukkakaalista ja punasipulista.', '700 g vesimelonia, 300 g kukkakaalia, 2 punasipulia, 2 rkl oliiviöljyä, 2 rkl balsamicoa, 1/2 tl suolaa', 'Kuutioi vesimeloni. Jaa kukkakaali pieniksi suupaloiksi käsin tai veitsellä. Viipaloi punasipulit. Yhdistä meloni, kukkakaali ja sipuli kulhossa. Kääntele sekaan öljy, balsamico ja suola.', 6);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Raparperisangria', 'Kesän ensimmäisten lämpimien päivien ilo on kuohuviinillä virkistetty hedelmäinen sangria.', '2 raparperinvartta, 1 dl vettä, 3/4 dl sokeria, 2 appelsiinia, 250 g mansikoita, 1 l kivennäisvettä, 750 ml kuohuviiniä, jääpaloja', 'Kuutioi raparperit. Kiehauta vesi ja sokeri kattilassa. Lisää raparperit liemeen ja siirrä kattila sivuun. Anna jäähtyä 30 minuuttia. Purista yhden appelsiinin mehu kannuun tai boolimaljaan. Pese toinen appelsiini huolellisesti ja viipaloi se kuorineen. Viipaloi mansikat. (Jos käytät pakastemansikoita, lisää ne booliin jäisinä.) Kaada raparperit liemineen, kivennäisvesi ja viini booliin. Lisää hedelmät ja jääpalat ja tarjoa heti.', 9);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Suklaamousse', 'Suklaamousse on maukas jälkiruoka, jonka voi maustaa konjakilla.', '200 g taloussuklaata, 50 g voita, 2 keltuaista, 2 rkl konjakkia halutessasi, 2 valkuaista, 3 dl kuohukermaa', 'Paloittele suklaa ja voi kattilaan. Kuumenna seosta miedolla lämmöllä, kunnes se sulaa. Nosta kattila pois liedeltä. Erottele keltuaiset ja valkuaiset eri kulhoihin. Lisää keltuaiset suklaaseokseen yksitellen voimakkaasti vatkaten. Mausta seos halutessasi konjakilla ja anna jäähtyä. Vatkaa kerma ja valkuaiset erikseen vaahdoksi. Sekoita vaahdot varovaisesti suklaaseokseen. Jaa vaahto annosmaljoihin ja anna hyytyä jääkaapissa muutaman tunnin.', 7);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Lihamakaronilaatikko', 'Lihamakaronilaatikko on suosikkiruoka, jonka kanssa maistuu raikas salaatti.', '5 dl makaronia, 1 1/2 l vettä, 3 lihaliemikuutiota, 1 sipuli, 300 g jauhelihaa, 1/2 tl suolaa, 1/2 tl paprikajauhetta, 1/4 tl mustapippurirouhetta, 5 dl maitoa, 2 munaa, 1/2 tl kuivattua basilikaa, 1 1/2 dl juustoraastetta', 'Keitä makaronit lihaliemessä melkein kypsiksi ja valuta huolellisesti. Kuori ja hienonna sipuli, jos et käytä pakastettua. Ruskista jauheliha ja hienonnettu sipuli pannulla. Lisää mausteet. Sekoita makaronit ja jauhelihaseos keskenään ja kaada voideltuun uunivuokaan. Valmista munamaito sekoittamalla ja kaada tasaisesti laatikon pinnalle. Paista 200 asteessa noin 40 min.', 1);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Pähkinäinen porkkanapasta', 'Kasvisnauhapasta syntyy vuolemalla kuorimaveitsellä porkkanoita.', '500 g porkkanoita, 12 kirsikkatomaattia, 2 dl cashewpähkinöitä tai manteleita, ruukku basilikaa, 1/2 sitruunan mehu, 2 valkosipulinkynttä, 4 rkl oliiviöljyä, 3/4 tl suolaa, 1/2 tl mustapippuria', 'Kuori porkkanat, leikkaa kuorimaveitsellä nauhoiksi tai paloittele veitsellä. Paahda pähkinät kevyesti kuivalla pannulla. Rouhi pähkinät. Silppua basilika ja valkosipulinkynnet. Kuumenna öljy kasarissa, lisää porkkananauhat ja valkosipulisilppu. Kuumenna pari minuuttia. Lisää tomaatit ja pähkinät. Kuumenna nopeasti. Mausta sitruunamehulla, suolalla, mustapippurilla ja basilikasilpulla.', 3);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Lohiperhoset', 'Lohiperhoset ovat kalaruokien klassikko!', '4 (600 g) lohifileetä, 1/2 tl suolaa, rouhittua mustapippuria, 2 rkl öljyä', 'Tee lohipaloista perhosia leikkaamalla palan keskelle nahkaan ulottuva viilto. Taita perhosen muotoon niin, että nahkapuolet ovat vastakkain. Mausta suolalla ja pippurilla. Paista öljyssä kummaltakin puolelta. Pidä lämpimänä alumiinifolion alla. Tarjoa lohiperhoset bataattimuusin ja omena-rosmariinikastikkeen kanssa.', 2);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Nutellakeksit', 'Nutellakeksit valmistuvat nopeasti ja sopivat kahvipöytään ja ruokalahjaksi.', '150 g voita, 2 dl nutellaa, 2 1/2 dl sokeria, 2 kananmunaa, 5 dl vehnäjauhoja, 1/2 dl kaakaojauhetta, 1/2 tl suolaa, 100 g valkosuklaahippuja', 'Vaahdota voi, nutella ja sokeri. Lisää munat yksitellen hyvin vatkaten. Lisää keskenään sekoitetut kuivat aineet ja sekoita tasaiseksi. Ripottele reilu puolet valkosuklaahipuista taikinaan ja kääntele ne kevyesti joukkoon. Pyörittele taikinasta isoja, lihapullan kokoisia palloja ja nosta leivinpaperoidulle uunipellille. Jätä leviämisvaraa. Paista yksi pellillinen kerrallaan. Painele keksit pinnalta tasaisiksi ja ripottele pinnalle loput valkosuklaahippuset. Painele hippusia hieman taikinan sisään. Paista 200-asteisessa uunissa noin 10 minuuttia.', 8);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Hernekeitto', 'Tarjoa keiton kanssa pekonia, smetanaa ja sinappia.', '500 g kuivattuja herneitä, 2 1/2 l vettä, 2 porkkanaa, 150 g juuriselleriä, 2 sipulia, 2 tl suolaa, 1 tl mustapippuria, 3 tl meiramia, LISÄKSI: 125 g pekonia, 2 dl smetanaa, sinappia', 'Liota herneitä yön yli vedessä. Kaada vesi pois ja pane herneet kattilaan. Lisää vesi ja silputut sipulit. Anna kiehua hetki ja kuori pois pinnalle nouseva vaahto. Lisää suola ja pippuri. Keitä hiljalleen 2 tuntia. Lisää kuutioidut juurekset ja keitä vielä noin 1/2 tuntia. Lisää tarvittaessa vettä. Mausta meiramilla ja lisää muita mausteita tarvittaessa. Tarjoa keiton kanssa paistettua ja murennettua pekonia, smetanaa ja sinappia.', 5);

insert into recipe(name, description, ingredients, instructions, categoryid) values ('Helppo kanawokki', 'Nopea ja helppo vokki valmistuu noin viidessä minuutissa, kun käytät jauhelihaa ja käyttövalmista tuoretta kasvissekoitusta.', '400 g broilerin jauhelihaa, 400 g tuoretta wok-kasvissekoitusta, 2 rkl öljyä, 2 rkl soijakastiketta, 2 rkl chilikastiketta, 1/4 tl mustapippuria, 1/2 tl suolaa, PINNALLE: 1/2 limetin mehu, tuoretta korianteria, suolapähkinöitä', 'Kuumenna 1 rkl öljyä vokissa. Lisää jauheliha ja paista se sekoitelleen kypsäksi. Lisää vokkiin soijakastike ja chilikastike. Mausta suolalla ja pippurilla. Kuumenna ja kaada jauheliha pois vokista. Lisää 1 rkl öljyä ja kuumenna vokki. Kaada kasvikset vokkiin ja kuumenna sekoitelleen 2 minuuttia. Lisää jauheliha ja sekoita. Lisää pinnalle limetin mehua, korianteria ja pähkinöitä. Tarjoa lisänä riisiä.', 4);
