insert into recipe(name, description, ingredients, instructions) values ('Lihapullat uunissa', 'Lihapullien perustaikina ja kermakastike on yksi Yhteishyvän lukijoiden suosikkiresepteistä. Nämä maukkaat lihapullat maistuvat kaikille!', '2 dl vettä (tai kermaa tai kermaviiliä), 1 dl korppujauhoja, 1 kpl sipuli, 1 rkl, öljyä, 1 kpl kananmuna, 2 tl paprikajauhetta, 1 tl suolaa, 1/2 tl mustapippuria, 400 g jauhelihaa', 'Sekoita korppujauhot nesteeseen ja anna imeytyä. Kuori ja hienonna sipuli. Kuullota sipuli öljyssä pannulla. Lisää sipuli, muna, mausteet ja jauhelina korppujauhoseokseen. Sekoita tasaiseksi.');
insert into recipe(name, description, ingredients, instructions) values ('Helppo särkikiusaus', 'Kotimaisesta särjestä ja pakasteperunoista syntyy vaivaton uuniruoka, joka on janssoninkiusauksen pikkuserkku.', '2 dl vettä (tai kermaa tai kermaviiliä), 1 dl korppujauhoja, 1 kpl sipuli, 1 rkl, öljyä, 1 kpl kananmuna, 2 tl paprikajauhetta, 1 tl suolaa, 1/2 tl mustapippuria, 400 g jauhelihaa', 'Säädä uuni 200 asteeseen. Kaada uunivuokaan puolet peruna-sipulisekoituksesta. Irrottele kala pienemmiksi paloiksi ja lisää vuokaan. Laita päälle loppu peruna-sipulisekoitus.');
insert into recipe(name, description, ingredients, instructions) values ('Kesäkurpitsa-halloumipihvit ja limetti-jogurttikastike', 'Helpot kasvispihvit valmistuvat nopeasti kesäkurpitsasta ja halloumijuustosta. Näiden pihvien paistamiseen tarvitset vain muutaman aineksen. Nauti yhdessä limetti-jogurttikastikkeen kanssa.', '2 dl vettä (tai kermaa tai kermaviiliä), 1 dl korppujauhoja, 1 kpl sipuli, 1 rkl, öljyä, 1 kpl kananmuna, 2 tl paprikajauhetta, 1 tl suolaa, 1/2 tl mustapippuria, 400 g jauhelihaa', 'Sekoita kastikkeen ainekset keskenään ja anna sen maustua pihvien teon ajan');
insert into recipe(name, description, ingredients, instructions) values ('Kaura-porkkanasämpylät', 'Mehevät kaura-porkkanasämpylät maistuvat tuoreina voin kera.
', '2 dl vettä (tai kermaa tai kermaviiliä), 1 dl korppujauhoja, 1 kpl sipuli, 1 rkl, öljyä, 1 kpl kananmuna, 2 tl paprikajauhetta, 1 tl suolaa, 1/2 tl mustapippuria, 400 g jauhelihaa', 'Sekoita omenamehu ja kermaviili keskenään ja lämmitä seos kädenlämpöiseksi. Murenna joukkoon hiiva. Lisää suola ja hunaja. Kuori ja raasta porkkanat hienoksi, lisää joukkoon. Alusta sämpyläjauhot ja kaurahiutaleet taikinaan vähitellen vaivaten. Lisää lopuksi öljy.

Anna kohota peitettynä lämpimässä paikassa kaksinkertaiseksi. Kaada taikina jauhotetulle alustalle ja leivo se kahdeksi tangoksi. Leikkaa tangot paloiksi ja pyöritä paloista sämpylöitä. Anna kohota peitettynä noin 20 minuuttia. Kuumenna uuni 225 asteeseen. Paista uunissa noin 10 minuuttia.');


